apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-cost-optimizer
spec:
  replicas: 3
  selector:
    matchLabels:
      app: optimizer
  template:
    metadata:
      labels:
        app: optimizer
    spec:
      containers:
      - name: data-collector
        image: cloud-cost-optimizer-data-collector:latest
        ports:
        - containerPort: 5000
      - name: cost-analyzer
        image: cloud-cost-optimizer-cost-analysis:latest
        ports:
        - containerPort: 5000
      - name: web
        image: cloud-cost-optimizer-web:latest
        ports:
        - containerPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cost-analysis-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cost-analysis
  template:
    metadata:
      labels:
        app: cost-analysis
    spec:
      containers:
      - name: cost-analysis-container
        image: cost-analysis-service:latest
        ports:
        - containerPort: 5001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-dashboard-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-dashboard
  template:
    metadata:
      labels:
        app: web-dashboard
    spec:
      containers:
      - name: web-dashboard-container
        image: web-dashboard-service:latest
        ports:
        - containerPort: 5000
