apiVersion: v1
kind: Service
metadata:
  name: cost-analysis-service
spec:
  selector:
    app: cost-analysis
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: web-dashboard-service
spec:
  selector:
    app: web-dashboard
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
