apiVersion: v1
kind: PersistentVolume
metadata:
  name: cost-analysis-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/cost-analysis"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cost-analysis-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
